---
title: "202833 Teaching materials"
subtitle: 'Statistics for Bioscience Research'
author: "Pimonrat Tiansawat (Chiang Mai University)"
date: "`r format(Sys.Date(), '%B, %Y')`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: book.bib
biblio-style: apalike
link-citations: yes
github-repo: Pimorc/202833
description: "This is material for 202833 course at the Department of Biology, Chiang Mai University"
---

# Preface {-}

These materials are for the course "Statistics for Bioscience Research" (Course code 202833), taught by the author. All analyses and visualizations are done in the R programming language [@R-base], and RStudio [@rstudio] is used as a graphical interface for R. The materials are designed for graduate students across multiple curricula. The materials are divided into 14 sessions (1.5 hours each), totaling 21 hours.

The lessons include:-

| Course Contents | Lab ID     |
|:------------------------|------------------------|
| 1\. Introduction to R | Lab \@ref(basic1), \@ref(basic2)  |
| 2\. Descriptive statistics | Lab \@ref(eda1), \@ref(eda2)     |
| 3\. Statistical tests in R  | Lab \@ref(tests)|
| 4\. Multivariate analyses| Lab \@ref(pca), \@ref(lda) |

At the end of this class, students will work on a term project. The students are encourage to use their own dataset. If the students do not have one, the dataset is provided. Please go to Term Project folder for instructions and the dataset. [Click here to download the folder](https://o365cmu-my.sharepoint.com/:f:/g/personal/pimonrat_t_cmu_ac_th/IgDi-NkKPmHaS6mZxEJAsyGWASfgAAGFz3k3ej3UBc-Ezno?e=v0YiCH)

The illustrations in this material consist of images taken or created by the author, as well as images obtained from other sources, including articles published in academic journals by the author. R programming language [@R-base] is used for the examples of analyses and visualization. RStudio [@rstudio] is used as a coding environment. An R package, `bookdown` [@R-bookdown], is used for typesetting the lecture and lab materials.

